
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Sep 26 18:35:48 CEST 2012
//----------------------------------------------------

package parser;

import java.util.Collections;
import java.util.LinkedList;
import java.util.List;

import python_program.Program;
import python_program.expression.BinaryExpression;
import python_program.expression.Expression;
import python_program.expression.FalseExpression;
import python_program.expression.FloatExpression;
import python_program.expression.FunctionExpression;
import python_program.expression.IdentifierExpression;
import python_program.expression.InputExpression;
import python_program.expression.IntegerExpression;
import python_program.expression.LambdaExpression;
import python_program.expression.ListExpression;
import python_program.expression.ParenthesesExpression;
import python_program.expression.SubscriptionExpression;
import python_program.expression.TrueExpression;
import python_program.expression.UnaryExpression;
import python_program.operators.BinaryOperators;
import python_program.operators.UnaryOperators;
import python_program.statement.AssignStatement;
import python_program.statement.ExpressionStatement;
import python_program.statement.FunctionDefinitionStatement;
import python_program.statement.IfElseStatement;
import python_program.statement.IfStatement;
import python_program.statement.PassStatement;
import python_program.statement.PrintStatement;
import python_program.statement.ReturnStatement;
import python_program.statement.Statement;
import python_program.statement.TargetAssignStatement;
import python_program.statement.WhileStatement;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Wed Sep 26 18:35:48 CEST 2012
  */
public class ParserCup extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public ParserCup() {super();}

  /** Constructor which sets the default scanner. */
  public ParserCup(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserCup(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\102\000\002\002\003\000\002\002\004\000\002\003" +
    "\004\000\002\003\003\000\002\015\004\000\002\015\004" +
    "\000\002\015\002\000\002\005\004\000\002\005\002\000" +
    "\002\004\004\000\002\004\003\000\002\004\005\000\002" +
    "\004\003\000\002\004\005\000\002\004\004\000\002\007" +
    "\005\000\002\007\003\000\002\007\002\000\002\006\003" +
    "\000\002\006\004\000\002\006\004\000\002\006\004\000" +
    "\002\006\005\000\002\006\005\000\002\006\005\000\002" +
    "\006\005\000\002\006\005\000\002\006\005\000\002\006" +
    "\005\000\002\006\005\000\002\006\005\000\002\006\005" +
    "\000\002\006\005\000\002\006\005\000\002\006\005\000" +
    "\002\006\005\000\002\006\005\000\002\006\005\000\002" +
    "\006\003\000\002\006\003\000\002\006\003\000\002\006" +
    "\003\000\002\006\005\000\002\006\003\000\002\006\005" +
    "\000\002\006\006\000\002\006\005\000\002\006\007\000" +
    "\002\010\011\000\002\010\006\000\002\010\006\000\002" +
    "\010\010\000\002\010\012\000\002\011\005\000\002\011" +
    "\003\000\002\012\004\000\002\012\003\000\002\013\004" +
    "\000\002\013\006\000\002\014\004\000\002\014\003\000" +
    "\002\020\006\000\002\021\003\000\002\022\005\000\002" +
    "\022\002\000\002\023\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\203\000\052\002\ufffb\004\030\005\007\006\027\014" +
    "\034\016\004\017\031\021\011\032\014\033\026\034\015" +
    "\036\022\040\013\041\025\042\016\044\010\050\037\055" +
    "\040\056\024\057\012\001\002\000\004\014\204\001\002" +
    "\000\004\002\001\001\002\000\052\002\ufffb\004\030\005" +
    "\007\006\027\014\034\016\004\017\031\021\011\032\014" +
    "\033\026\034\015\036\022\040\013\041\025\042\016\044" +
    "\010\050\037\055\040\056\024\057\012\001\002\000\032" +
    "\005\007\006\027\014\034\016\004\017\031\021\011\032" +
    "\014\033\026\036\022\040\044\050\037\055\040\001\002" +
    "\000\032\005\007\006\027\014\034\016\004\017\031\021" +
    "\011\032\014\033\026\036\022\040\044\050\037\055\040" +
    "\001\002\000\032\005\007\006\027\014\034\016\004\017" +
    "\031\021\011\032\014\033\026\036\022\040\044\050\037" +
    "\055\040\001\002\000\032\005\007\006\027\014\034\016" +
    "\004\017\031\021\011\032\014\033\026\036\022\040\044" +
    "\050\037\055\040\001\002\000\100\002\uffd8\004\uffd8\005" +
    "\uffd8\006\uffd8\010\uffd8\011\uffd8\012\uffd8\013\uffd8\014\uffd8" +
    "\016\uffd8\017\uffd8\021\uffd8\022\uffd8\023\uffd8\024\uffd8\025" +
    "\uffd8\026\uffd8\027\uffd8\030\uffd8\031\uffd8\032\uffd8\033\uffd8" +
    "\036\uffd8\040\uffd8\041\uffd8\042\uffd8\043\173\045\uffd8\050" +
    "\uffd8\055\uffd8\057\uffd8\001\002\000\106\002\uffda\004\uffda" +
    "\005\uffda\006\uffda\010\uffda\011\uffda\012\uffda\013\uffda\014" +
    "\uffda\015\uffda\016\uffda\017\uffda\020\uffda\021\uffda\022\uffda" +
    "\023\uffda\024\uffda\025\uffda\026\uffda\027\uffda\030\uffda\031" +
    "\uffda\032\uffda\033\uffda\036\uffda\037\uffda\040\uffda\041\uffda" +
    "\042\uffda\045\uffda\050\uffda\051\uffda\055\uffda\057\uffda\001" +
    "\002\000\032\005\007\006\027\014\034\016\004\017\031" +
    "\021\011\032\014\033\026\036\022\040\044\050\037\055" +
    "\040\001\002\000\046\002\ufff7\004\ufff7\005\ufff7\006\ufff7" +
    "\014\ufff7\016\ufff7\017\ufff7\021\ufff7\032\ufff7\033\ufff7\036" +
    "\ufff7\040\ufff7\041\ufff7\042\ufff7\045\ufff7\050\ufff7\055\ufff7" +
    "\057\ufff7\001\002\000\054\002\uffc9\004\uffc9\005\uffc9\006" +
    "\uffc9\014\uffc9\016\uffc9\017\uffc9\021\uffc9\032\uffc9\033\uffc9" +
    "\034\uffc9\036\uffc9\040\uffc9\041\uffc9\042\uffc9\044\uffc9\047" +
    "\uffc9\050\uffc9\055\uffc9\056\uffc9\057\uffc9\001\002\000\004" +
    "\002\164\001\002\000\004\041\163\001\002\000\106\002" +
    "\uffdb\004\uffdb\005\uffdb\006\uffdb\010\uffdb\011\uffdb\012\uffdb" +
    "\013\uffdb\014\uffdb\015\uffdb\016\uffdb\017\uffdb\020\uffdb\021" +
    "\uffdb\022\uffdb\023\uffdb\024\uffdb\025\uffdb\026\uffdb\027\uffdb" +
    "\030\uffdb\031\uffdb\032\uffdb\033\uffdb\036\uffdb\037\uffdb\040" +
    "\uffdb\041\uffdb\042\uffdb\045\uffdb\050\uffdb\051\uffdb\055\uffdb" +
    "\057\uffdb\001\002\000\076\002\ufff5\004\ufff5\005\056\006" +
    "\046\010\052\011\060\012\050\013\053\014\064\016\ufff5" +
    "\017\ufff5\021\ufff5\022\061\023\054\024\055\025\057\026" +
    "\063\027\051\030\065\031\047\032\ufff5\033\ufff5\036\ufff5" +
    "\040\ufff5\041\ufff5\042\ufff5\045\ufff5\050\062\055\ufff5\057" +
    "\ufff5\001\002\000\004\040\141\001\002\000\052\002\ufffb" +
    "\004\030\005\007\006\027\014\034\016\004\017\031\021" +
    "\011\032\014\033\026\034\015\036\022\040\013\041\025" +
    "\042\016\044\010\050\037\055\040\056\024\057\012\001" +
    "\002\000\106\002\uffd9\004\uffd9\005\uffd9\006\uffd9\010\uffd9" +
    "\011\uffd9\012\uffd9\013\uffd9\014\uffd9\015\uffd9\016\uffd9\017" +
    "\uffd9\020\uffd9\021\uffd9\022\uffd9\023\uffd9\024\uffd9\025\uffd9" +
    "\026\uffd9\027\uffd9\030\uffd9\031\uffd9\032\uffd9\033\uffd9\036" +
    "\uffd9\037\uffd9\040\uffd9\041\uffd9\042\uffd9\045\uffd9\050\uffd9" +
    "\051\uffd9\055\uffd9\057\uffd9\001\002\000\032\005\007\006" +
    "\027\014\034\016\004\017\031\021\011\032\014\033\026" +
    "\036\022\040\044\050\037\055\040\001\002\000\050\002" +
    "\ufff0\004\ufff0\005\007\006\027\014\034\016\004\017\031" +
    "\020\ufff0\021\011\032\014\033\026\036\022\040\044\041" +
    "\ufff0\042\ufff0\045\ufff0\050\037\055\040\057\ufff0\001\002" +
    "\000\106\002\uffef\004\uffef\005\uffef\006\uffef\010\uffef\011" +
    "\uffef\012\uffef\013\uffef\014\uffef\015\uffef\016\uffef\017\uffef" +
    "\020\uffef\021\uffef\022\uffef\023\uffef\024\uffef\025\uffef\026" +
    "\uffef\027\uffef\030\uffef\031\uffef\032\uffef\033\uffef\036\uffef" +
    "\037\uffef\040\uffef\041\uffef\042\uffef\045\uffef\050\uffef\051" +
    "\uffef\055\uffef\057\uffef\001\002\000\100\002\uffd6\004\uffd6" +
    "\005\uffd6\006\uffd6\010\uffd6\011\uffd6\012\uffd6\013\uffd6\014" +
    "\uffd6\016\uffd6\017\uffd6\021\uffd6\022\uffd6\023\uffd6\024\uffd6" +
    "\025\uffd6\026\uffd6\027\uffd6\030\uffd6\031\uffd6\032\uffd6\033" +
    "\uffd6\036\uffd6\040\uffd6\041\uffd6\042\uffd6\043\uffc3\045\uffd6" +
    "\050\uffd6\055\uffd6\057\uffd6\001\002\000\004\002\ufffe\001" +
    "\002\000\032\005\007\006\027\014\034\016\004\017\031" +
    "\021\011\032\014\033\026\036\022\040\044\050\037\055" +
    "\040\001\002\000\046\002\ufff9\004\030\005\007\006\027" +
    "\014\034\016\004\017\031\021\011\032\014\033\026\036" +
    "\022\040\013\041\uffcb\042\016\045\126\050\037\055\040" +
    "\057\012\001\002\000\004\043\124\001\002\000\036\005" +
    "\007\006\027\014\034\016\004\017\031\020\ufff0\021\011" +
    "\032\014\033\026\036\022\040\044\050\037\051\ufff0\055" +
    "\040\001\002\000\006\037\042\040\041\001\002\000\006" +
    "\020\115\037\uffc1\001\002\000\032\005\007\006\027\014" +
    "\034\016\004\017\031\021\011\032\014\033\026\036\022" +
    "\040\044\050\037\055\040\001\002\000\106\002\uffd3\004" +
    "\uffd3\005\056\006\046\010\052\011\060\012\050\013\053" +
    "\014\064\015\uffd3\016\uffd3\017\uffd3\020\uffd3\021\uffd3\022" +
    "\061\023\054\024\055\025\057\026\063\027\051\030\065" +
    "\031\047\032\uffd3\033\uffd3\036\uffd3\037\uffd3\040\uffd3\041" +
    "\uffd3\042\uffd3\045\uffd3\050\062\051\uffd3\055\uffd3\057\uffd3" +
    "\001\002\000\106\002\uffd8\004\uffd8\005\uffd8\006\uffd8\010" +
    "\uffd8\011\uffd8\012\uffd8\013\uffd8\014\uffd8\015\uffd8\016\uffd8" +
    "\017\uffd8\020\uffd8\021\uffd8\022\uffd8\023\uffd8\024\uffd8\025" +
    "\uffd8\026\uffd8\027\uffd8\030\uffd8\031\uffd8\032\uffd8\033\uffd8" +
    "\036\uffd8\037\uffd8\040\uffd8\041\uffd8\042\uffd8\045\uffd8\050" +
    "\uffd8\051\uffd8\055\uffd8\057\uffd8\001\002\000\106\002\uffd6" +
    "\004\uffd6\005\uffd6\006\uffd6\010\uffd6\011\uffd6\012\uffd6\013" +
    "\uffd6\014\uffd6\015\uffd6\016\uffd6\017\uffd6\020\uffd6\021\uffd6" +
    "\022\uffd6\023\uffd6\024\uffd6\025\uffd6\026\uffd6\027\uffd6\030" +
    "\uffd6\031\uffd6\032\uffd6\033\uffd6\036\uffd6\037\uffd6\040\uffd6" +
    "\041\uffd6\042\uffd6\045\uffd6\050\uffd6\051\uffd6\055\uffd6\057" +
    "\uffd6\001\002\000\032\005\007\006\027\014\034\016\004" +
    "\017\031\021\011\032\014\033\026\036\022\040\044\050" +
    "\037\055\040\001\002\000\032\005\007\006\027\014\034" +
    "\016\004\017\031\021\011\032\014\033\026\036\022\040" +
    "\044\050\037\055\040\001\002\000\032\005\007\006\027" +
    "\014\034\016\004\017\031\021\011\032\014\033\026\036" +
    "\022\040\044\050\037\055\040\001\002\000\032\005\007" +
    "\006\027\014\034\016\004\017\031\021\011\032\014\033" +
    "\026\036\022\040\044\050\037\055\040\001\002\000\032" +
    "\005\007\006\027\014\034\016\004\017\031\021\011\032" +
    "\014\033\026\036\022\040\044\050\037\055\040\001\002" +
    "\000\032\005\007\006\027\014\034\016\004\017\031\021" +
    "\011\032\014\033\026\036\022\040\044\050\037\055\040" +
    "\001\002\000\032\005\007\006\027\014\034\016\004\017" +
    "\031\021\011\032\014\033\026\036\022\040\044\050\037" +
    "\055\040\001\002\000\032\005\007\006\027\014\034\016" +
    "\004\017\031\021\011\032\014\033\026\036\022\040\044" +
    "\050\037\055\040\001\002\000\032\005\007\006\027\014" +
    "\034\016\004\017\031\021\011\032\014\033\026\036\022" +
    "\040\044\050\037\055\040\001\002\000\032\005\007\006" +
    "\027\014\034\016\004\017\031\021\011\032\014\033\026" +
    "\036\022\040\044\050\037\055\040\001\002\000\032\005" +
    "\007\006\027\014\034\016\004\017\031\021\011\032\014" +
    "\033\026\036\022\040\044\050\037\055\040\001\002\000" +
    "\032\005\007\006\027\014\034\016\004\017\031\021\011" +
    "\032\014\033\026\036\022\040\044\050\037\055\040\001" +
    "\002\000\032\005\007\006\027\014\034\016\004\017\031" +
    "\021\011\032\014\033\026\036\022\040\044\050\037\055" +
    "\040\001\002\000\032\005\007\006\027\014\034\016\004" +
    "\017\031\021\011\032\014\033\026\036\022\040\044\050" +
    "\037\055\040\001\002\000\036\005\007\006\027\014\034" +
    "\015\067\016\004\017\031\020\ufff0\021\011\032\014\033" +
    "\026\036\022\040\044\050\037\055\040\001\002\000\032" +
    "\005\007\006\027\014\034\016\004\017\031\021\011\032" +
    "\014\033\026\036\022\040\044\050\037\055\040\001\002" +
    "\000\106\002\uffdf\004\uffdf\005\056\006\046\010\052\011" +
    "\060\012\050\013\053\014\064\015\uffdf\016\uffdf\017\uffdf" +
    "\020\uffdf\021\uffdf\022\061\023\054\024\055\025\057\026" +
    "\063\027\051\030\uffdf\031\047\032\uffdf\033\uffdf\036\uffdf" +
    "\037\uffdf\040\uffdf\041\uffdf\042\uffdf\045\uffdf\050\062\051" +
    "\uffdf\055\uffdf\057\uffdf\001\002\000\106\002\uffd5\004\uffd5" +
    "\005\uffd5\006\uffd5\010\uffd5\011\uffd5\012\uffd5\013\uffd5\014" +
    "\uffd5\015\uffd5\016\uffd5\017\uffd5\020\uffd5\021\uffd5\022\uffd5" +
    "\023\uffd5\024\uffd5\025\uffd5\026\uffd5\027\uffd5\030\uffd5\031" +
    "\uffd5\032\uffd5\033\uffd5\036\uffd5\037\uffd5\040\uffd5\041\uffd5" +
    "\042\uffd5\045\uffd5\050\uffd5\051\uffd5\055\uffd5\057\uffd5\001" +
    "\002\000\104\002\ufff1\004\ufff1\005\056\006\046\010\052" +
    "\011\060\012\050\013\053\014\064\015\ufff1\016\ufff1\017" +
    "\ufff1\020\ufff1\021\ufff1\022\061\023\054\024\055\025\057" +
    "\026\063\027\051\030\065\031\047\032\ufff1\033\ufff1\036" +
    "\ufff1\040\ufff1\041\ufff1\042\ufff1\045\ufff1\050\062\051\ufff1" +
    "\055\ufff1\057\ufff1\001\002\000\006\015\073\020\072\001" +
    "\002\000\032\005\007\006\027\014\034\016\004\017\031" +
    "\021\011\032\014\033\026\036\022\040\044\050\037\055" +
    "\040\001\002\000\106\002\uffd4\004\uffd4\005\uffd4\006\uffd4" +
    "\010\uffd4\011\uffd4\012\uffd4\013\uffd4\014\uffd4\015\uffd4\016" +
    "\uffd4\017\uffd4\020\uffd4\021\uffd4\022\uffd4\023\uffd4\024\uffd4" +
    "\025\uffd4\026\uffd4\027\uffd4\030\uffd4\031\uffd4\032\uffd4\033" +
    "\uffd4\036\uffd4\037\uffd4\040\uffd4\041\uffd4\042\uffd4\045\uffd4" +
    "\050\uffd4\051\uffd4\055\uffd4\057\uffd4\001\002\000\104\002" +
    "\ufff2\004\ufff2\005\056\006\046\010\052\011\060\012\050" +
    "\013\053\014\064\015\ufff2\016\ufff2\017\ufff2\020\ufff2\021" +
    "\ufff2\022\061\023\054\024\055\025\057\026\063\027\051" +
    "\030\065\031\047\032\ufff2\033\ufff2\036\ufff2\040\ufff2\041" +
    "\ufff2\042\ufff2\045\ufff2\050\062\051\ufff2\055\ufff2\057\ufff2" +
    "\001\002\000\106\002\uffe1\004\uffe1\005\056\006\046\010" +
    "\052\011\060\012\050\013\053\014\064\015\uffe1\016\uffe1" +
    "\017\uffe1\020\uffe1\021\uffe1\022\uffe1\023\uffe1\024\uffe1\025" +
    "\uffe1\026\uffe1\027\uffe1\030\uffe1\031\uffe1\032\uffe1\033\uffe1" +
    "\036\uffe1\037\uffe1\040\uffe1\041\uffe1\042\uffe1\045\uffe1\050" +
    "\062\051\uffe1\055\uffe1\057\uffe1\001\002\000\044\005\056" +
    "\006\046\010\052\011\060\012\050\013\053\014\064\022" +
    "\061\023\054\024\055\025\057\026\063\027\051\030\065" +
    "\031\047\050\062\051\077\001\002\000\110\002\uffc4\004" +
    "\uffc4\005\uffc4\006\uffc4\010\uffc4\011\uffc4\012\uffc4\013\uffc4" +
    "\014\uffc4\015\uffc4\016\uffc4\017\uffc4\020\uffc4\021\uffc4\022" +
    "\uffc4\023\uffc4\024\uffc4\025\uffc4\026\uffc4\027\uffc4\030\uffc4" +
    "\031\uffc4\032\uffc4\033\uffc4\036\uffc4\037\uffc4\040\uffc4\041" +
    "\uffc4\042\uffc4\043\uffc4\045\uffc4\050\uffc4\051\uffc4\055\uffc4" +
    "\057\uffc4\001\002\000\106\002\uffe5\004\uffe5\005\056\006" +
    "\046\010\052\011\060\012\050\013\053\014\064\015\uffe5" +
    "\016\uffe5\017\uffe5\020\uffe5\021\uffe5\022\uffe5\023\uffe5\024" +
    "\uffe5\025\uffe5\026\uffe5\027\uffe5\030\uffe5\031\uffe5\032\uffe5" +
    "\033\uffe5\036\uffe5\037\uffe5\040\uffe5\041\uffe5\042\uffe5\045" +
    "\uffe5\050\062\051\uffe5\055\uffe5\057\uffe5\001\002\000\106" +
    "\002\uffe8\004\uffe8\005\uffe8\006\uffe8\010\uffe8\011\uffe8\012" +
    "\050\013\uffe8\014\064\015\uffe8\016\uffe8\017\uffe8\020\uffe8" +
    "\021\uffe8\022\uffe8\023\uffe8\024\uffe8\025\uffe8\026\uffe8\027" +
    "\uffe8\030\uffe8\031\uffe8\032\uffe8\033\uffe8\036\uffe8\037\uffe8" +
    "\040\uffe8\041\uffe8\042\uffe8\045\uffe8\050\062\051\uffe8\055" +
    "\uffe8\057\uffe8\001\002\000\106\002\uffe2\004\uffe2\005\056" +
    "\006\046\010\052\011\060\012\050\013\053\014\064\015" +
    "\uffe2\016\uffe2\017\uffe2\020\uffe2\021\uffe2\022\uffe2\023\uffe2" +
    "\024\uffe2\025\uffe2\026\uffe2\027\uffe2\030\uffe2\031\uffe2\032" +
    "\uffe2\033\uffe2\036\uffe2\037\uffe2\040\uffe2\041\uffe2\042\uffe2" +
    "\045\uffe2\050\062\051\uffe2\055\uffe2\057\uffe2\001\002\000" +
    "\106\002\uffeb\004\uffeb\005\uffeb\006\uffeb\010\052\011\060" +
    "\012\050\013\053\014\064\015\uffeb\016\uffeb\017\uffeb\020" +
    "\uffeb\021\uffeb\022\uffeb\023\uffeb\024\uffeb\025\uffeb\026\uffeb" +
    "\027\uffeb\030\uffeb\031\uffeb\032\uffeb\033\uffeb\036\uffeb\037" +
    "\uffeb\040\uffeb\041\uffeb\042\uffeb\045\uffeb\050\062\051\uffeb" +
    "\055\uffeb\057\uffeb\001\002\000\106\002\uffe3\004\uffe3\005" +
    "\056\006\046\010\052\011\060\012\050\013\053\014\064" +
    "\015\uffe3\016\uffe3\017\uffe3\020\uffe3\021\uffe3\022\uffe3\023" +
    "\uffe3\024\uffe3\025\uffe3\026\uffe3\027\uffe3\030\uffe3\031\uffe3" +
    "\032\uffe3\033\uffe3\036\uffe3\037\uffe3\040\uffe3\041\uffe3\042" +
    "\uffe3\045\uffe3\050\062\051\uffe3\055\uffe3\057\uffe3\001\002" +
    "\000\106\002\uffe4\004\uffe4\005\056\006\046\010\052\011" +
    "\060\012\050\013\053\014\064\015\uffe4\016\uffe4\017\uffe4" +
    "\020\uffe4\021\uffe4\022\uffe4\023\uffe4\024\uffe4\025\uffe4\026" +
    "\uffe4\027\uffe4\030\uffe4\031\uffe4\032\uffe4\033\uffe4\036\uffe4" +
    "\037\uffe4\040\uffe4\041\uffe4\042\uffe4\045\uffe4\050\062\051" +
    "\uffe4\055\uffe4\057\uffe4\001\002\000\106\002\uffe7\004\uffe7" +
    "\005\uffe7\006\uffe7\010\uffe7\011\uffe7\012\050\013\uffe7\014" +
    "\064\015\uffe7\016\uffe7\017\uffe7\020\uffe7\021\uffe7\022\uffe7" +
    "\023\uffe7\024\uffe7\025\uffe7\026\uffe7\027\uffe7\030\uffe7\031" +
    "\uffe7\032\uffe7\033\uffe7\036\uffe7\037\uffe7\040\uffe7\041\uffe7" +
    "\042\uffe7\045\uffe7\050\062\051\uffe7\055\uffe7\057\uffe7\001" +
    "\002\000\106\002\uffe9\004\uffe9\005\uffe9\006\uffe9\010\uffe9" +
    "\011\uffe9\012\050\013\uffe9\014\064\015\uffe9\016\uffe9\017" +
    "\uffe9\020\uffe9\021\uffe9\022\uffe9\023\uffe9\024\uffe9\025\uffe9" +
    "\026\uffe9\027\uffe9\030\uffe9\031\uffe9\032\uffe9\033\uffe9\036" +
    "\uffe9\037\uffe9\040\uffe9\041\uffe9\042\uffe9\045\uffe9\050\062" +
    "\051\uffe9\055\uffe9\057\uffe9\001\002\000\106\002\uffe0\004" +
    "\uffe0\005\056\006\046\010\052\011\060\012\050\013\053" +
    "\014\064\015\uffe0\016\uffe0\017\uffe0\020\uffe0\021\uffe0\022" +
    "\uffe0\023\uffe0\024\uffe0\025\uffe0\026\uffe0\027\uffe0\030\uffe0" +
    "\031\uffe0\032\uffe0\033\uffe0\036\uffe0\037\uffe0\040\uffe0\041" +
    "\uffe0\042\uffe0\045\uffe0\050\062\051\uffe0\055\uffe0\057\uffe0" +
    "\001\002\000\106\002\uffe6\004\uffe6\005\uffe6\006\uffe6\010" +
    "\uffe6\011\uffe6\012\uffe6\013\uffe6\014\064\015\uffe6\016\uffe6" +
    "\017\uffe6\020\uffe6\021\uffe6\022\uffe6\023\uffe6\024\uffe6\025" +
    "\uffe6\026\uffe6\027\uffe6\030\uffe6\031\uffe6\032\uffe6\033\uffe6" +
    "\036\uffe6\037\uffe6\040\uffe6\041\uffe6\042\uffe6\045\uffe6\050" +
    "\062\051\uffe6\055\uffe6\057\uffe6\001\002\000\106\002\uffde" +
    "\004\uffde\005\056\006\046\010\052\011\060\012\050\013" +
    "\053\014\064\015\uffde\016\uffde\017\uffde\020\uffde\021\uffde" +
    "\022\061\023\054\024\055\025\057\026\063\027\051\030" +
    "\uffde\031\uffde\032\uffde\033\uffde\036\uffde\037\uffde\040\uffde" +
    "\041\uffde\042\uffde\045\uffde\050\062\051\uffde\055\uffde\057" +
    "\uffde\001\002\000\106\002\uffea\004\uffea\005\uffea\006\uffea" +
    "\010\052\011\060\012\050\013\053\014\064\015\uffea\016" +
    "\uffea\017\uffea\020\uffea\021\uffea\022\uffea\023\uffea\024\uffea" +
    "\025\uffea\026\uffea\027\uffea\030\uffea\031\uffea\032\uffea\033" +
    "\uffea\036\uffea\037\uffea\040\uffea\041\uffea\042\uffea\045\uffea" +
    "\050\062\051\uffea\055\uffea\057\uffea\001\002\000\004\037" +
    "\120\001\002\000\004\040\116\001\002\000\010\015\uffc1" +
    "\020\115\037\uffc1\001\002\000\006\015\uffc2\037\uffc2\001" +
    "\002\000\032\005\007\006\027\014\034\016\004\017\031" +
    "\021\011\032\014\033\026\036\022\040\044\050\037\055" +
    "\040\001\002\000\106\002\uffd2\004\uffd2\005\056\006\046" +
    "\010\052\011\060\012\050\013\053\014\064\015\uffd2\016" +
    "\uffd2\017\uffd2\020\uffd2\021\uffd2\022\061\023\054\024\055" +
    "\025\057\026\063\027\051\030\065\031\047\032\uffd2\033" +
    "\uffd2\036\uffd2\037\uffd2\040\uffd2\041\uffd2\042\uffd2\045\uffd2" +
    "\050\062\051\uffd2\055\uffd2\057\uffd2\001\002\000\006\020" +
    "\072\051\123\001\002\000\106\002\uffd7\004\uffd7\005\uffd7" +
    "\006\uffd7\010\uffd7\011\uffd7\012\uffd7\013\uffd7\014\uffd7\015" +
    "\uffd7\016\uffd7\017\uffd7\020\uffd7\021\uffd7\022\uffd7\023\uffd7" +
    "\024\uffd7\025\uffd7\026\uffd7\027\uffd7\030\uffd7\031\uffd7\032" +
    "\uffd7\033\uffd7\036\uffd7\037\uffd7\040\uffd7\041\uffd7\042\uffd7" +
    "\045\uffd7\050\uffd7\051\uffd7\055\uffd7\057\uffd7\001\002\000" +
    "\032\005\007\006\027\014\034\016\004\017\031\021\011" +
    "\032\014\033\026\036\022\040\044\050\037\055\040\001" +
    "\002\000\076\002\ufff4\004\ufff4\005\056\006\046\010\052" +
    "\011\060\012\050\013\053\014\064\016\ufff4\017\ufff4\021" +
    "\ufff4\022\061\023\054\024\055\025\057\026\063\027\051" +
    "\030\065\031\047\032\ufff4\033\ufff4\036\ufff4\040\ufff4\041" +
    "\ufff4\042\ufff4\045\ufff4\050\062\055\ufff4\057\ufff4\001\002" +
    "\000\040\004\030\005\007\006\027\014\034\016\004\017" +
    "\031\021\011\032\014\033\026\036\022\040\013\042\016" +
    "\050\037\055\040\057\012\001\002\000\004\002\uffff\001" +
    "\002\000\042\002\ufff9\004\030\005\007\006\027\014\034" +
    "\016\004\017\031\021\011\032\014\033\026\036\022\040" +
    "\013\042\016\050\037\055\040\057\012\001\002\000\004" +
    "\002\ufffa\001\002\000\004\041\uffcc\001\002\000\006\041" +
    "\uffcb\045\126\001\002\000\044\005\056\006\046\010\052" +
    "\011\060\012\050\013\053\014\064\015\135\022\061\023" +
    "\054\024\055\025\057\026\063\027\051\030\065\031\047" +
    "\050\062\001\002\000\106\002\uffdd\004\uffdd\005\uffdd\006" +
    "\uffdd\010\uffdd\011\uffdd\012\uffdd\013\uffdd\014\uffdd\015\uffdd" +
    "\016\uffdd\017\uffdd\020\uffdd\021\uffdd\022\uffdd\023\uffdd\024" +
    "\uffdd\025\uffdd\026\uffdd\027\uffdd\030\uffdd\031\uffdd\032\uffdd" +
    "\033\uffdd\036\uffdd\037\uffdd\040\uffdd\041\uffdd\042\uffdd\045" +
    "\uffdd\050\uffdd\051\uffdd\055\uffdd\057\uffdd\001\002\000\050" +
    "\002\ufff8\004\ufff8\005\ufff8\006\ufff8\014\ufff8\016\ufff8\017" +
    "\ufff8\020\072\021\ufff8\032\ufff8\033\ufff8\036\ufff8\040\ufff8" +
    "\041\ufff8\042\ufff8\045\ufff8\050\ufff8\055\ufff8\057\ufff8\001" +
    "\002\000\106\002\uffee\004\uffee\005\uffee\006\uffee\010\uffee" +
    "\011\uffee\012\050\013\uffee\014\064\015\uffee\016\uffee\017" +
    "\uffee\020\uffee\021\uffee\022\uffee\023\uffee\024\uffee\025\uffee" +
    "\026\uffee\027\uffee\030\uffee\031\uffee\032\uffee\033\uffee\036" +
    "\uffee\037\uffee\040\uffee\041\uffee\042\uffee\045\uffee\050\062" +
    "\051\uffee\055\uffee\057\uffee\001\002\000\004\002\ufffd\001" +
    "\002\000\004\014\142\001\002\000\006\015\143\040\144" +
    "\001\002\000\004\037\161\001\002\000\006\015\uffc1\020" +
    "\115\001\002\000\004\015\146\001\002\000\004\037\147" +
    "\001\002\000\042\004\030\005\007\006\027\014\034\016" +
    "\004\017\031\021\011\032\014\033\026\036\022\040\013" +
    "\041\151\042\016\050\037\055\040\057\012\001\002\000" +
    "\004\041\160\001\002\000\004\046\153\001\002\000\054" +
    "\002\uffcd\004\uffcd\005\uffcd\006\uffcd\014\uffcd\016\uffcd\017" +
    "\uffcd\021\uffcd\032\uffcd\033\uffcd\034\uffcd\036\uffcd\040\uffcd" +
    "\041\uffcd\042\uffcd\044\uffcd\047\uffcd\050\uffcd\055\uffcd\056" +
    "\uffcd\057\uffcd\001\002\000\046\004\030\005\007\006\027" +
    "\014\034\016\004\017\031\021\011\032\014\033\026\034" +
    "\015\036\022\040\013\042\016\044\010\050\037\055\040" +
    "\056\024\057\012\001\002\000\050\004\uffc5\005\uffc5\006" +
    "\uffc5\014\uffc5\016\uffc5\017\uffc5\021\uffc5\032\uffc5\033\uffc5" +
    "\034\uffc5\036\uffc5\040\uffc5\042\uffc5\044\uffc5\047\uffc5\050" +
    "\uffc5\055\uffc5\056\uffc5\057\uffc5\001\002\000\050\004\030" +
    "\005\007\006\027\014\034\016\004\017\031\021\011\032" +
    "\014\033\026\034\015\036\022\040\013\042\016\044\010" +
    "\047\157\050\037\055\040\056\024\057\012\001\002\000" +
    "\050\004\uffc6\005\uffc6\006\uffc6\014\uffc6\016\uffc6\017\uffc6" +
    "\021\uffc6\032\uffc6\033\uffc6\034\uffc6\036\uffc6\040\uffc6\042" +
    "\uffc6\044\uffc6\047\uffc6\050\uffc6\055\uffc6\056\uffc6\057\uffc6" +
    "\001\002\000\056\002\uffc7\004\uffc7\005\uffc7\006\uffc7\014" +
    "\uffc7\016\uffc7\017\uffc7\021\uffc7\032\uffc7\033\uffc7\034\uffc7" +
    "\035\uffc7\036\uffc7\040\uffc7\041\uffc7\042\uffc7\044\uffc7\047" +
    "\uffc7\050\uffc7\055\uffc7\056\uffc7\057\uffc7\001\002\000\056" +
    "\002\uffc8\004\uffc8\005\uffc8\006\uffc8\014\uffc8\016\uffc8\017" +
    "\uffc8\021\uffc8\032\uffc8\033\uffc8\034\uffc8\035\uffc8\036\uffc8" +
    "\040\uffc8\041\uffc8\042\uffc8\044\uffc8\047\uffc8\050\uffc8\055" +
    "\uffc8\056\uffc8\057\uffc8\001\002\000\042\004\030\005\007" +
    "\006\027\014\034\016\004\017\031\021\011\032\014\033" +
    "\026\036\022\040\013\041\151\042\016\050\037\055\040" +
    "\057\012\001\002\000\054\002\uffce\004\uffce\005\uffce\006" +
    "\uffce\014\uffce\016\uffce\017\uffce\021\uffce\032\uffce\033\uffce" +
    "\034\uffce\036\uffce\040\uffce\041\uffce\042\uffce\044\uffce\047" +
    "\uffce\050\uffce\055\uffce\056\uffce\057\uffce\001\002\000\054" +
    "\002\uffca\004\uffca\005\uffca\006\uffca\014\uffca\016\uffca\017" +
    "\uffca\021\uffca\032\uffca\033\uffca\034\uffca\036\uffca\040\uffca" +
    "\041\uffca\042\uffca\044\uffca\047\uffca\050\uffca\055\uffca\056" +
    "\uffca\057\uffca\001\002\000\004\002\000\001\002\000\044" +
    "\005\056\006\046\010\052\011\060\012\050\013\053\014" +
    "\064\022\061\023\054\024\055\025\057\026\063\027\051" +
    "\030\065\031\047\037\166\050\062\001\002\000\042\004" +
    "\030\005\007\006\027\014\034\016\004\017\031\021\011" +
    "\032\014\033\026\036\022\040\013\041\151\042\016\050" +
    "\037\055\040\057\012\001\002\000\056\002\uffd0\004\uffd0" +
    "\005\uffd0\006\uffd0\014\uffd0\016\uffd0\017\uffd0\021\uffd0\032" +
    "\uffd0\033\uffd0\034\uffd0\035\170\036\uffd0\040\uffd0\041\uffd0" +
    "\042\uffd0\044\uffd0\047\uffd0\050\uffd0\055\uffd0\056\uffd0\057" +
    "\uffd0\001\002\000\004\037\171\001\002\000\042\004\030" +
    "\005\007\006\027\014\034\016\004\017\031\021\011\032" +
    "\014\033\026\036\022\040\013\041\151\042\016\050\037" +
    "\055\040\057\012\001\002\000\054\002\uffd1\004\uffd1\005" +
    "\uffd1\006\uffd1\014\uffd1\016\uffd1\017\uffd1\021\uffd1\032\uffd1" +
    "\033\uffd1\034\uffd1\036\uffd1\040\uffd1\041\uffd1\042\uffd1\044" +
    "\uffd1\047\uffd1\050\uffd1\055\uffd1\056\uffd1\057\uffd1\001\002" +
    "\000\032\005\007\006\027\014\034\016\004\017\031\021" +
    "\011\032\014\033\026\036\022\040\044\050\037\055\040" +
    "\001\002\000\076\002\ufff6\004\ufff6\005\056\006\046\010" +
    "\052\011\060\012\050\013\053\014\064\016\ufff6\017\ufff6" +
    "\021\ufff6\022\061\023\054\024\055\025\057\026\063\027" +
    "\051\030\065\031\047\032\ufff6\033\ufff6\036\ufff6\040\ufff6" +
    "\041\ufff6\042\ufff6\045\ufff6\050\062\055\ufff6\057\ufff6\001" +
    "\002\000\076\002\ufff3\004\ufff3\005\056\006\046\010\052" +
    "\011\060\012\050\013\053\014\064\016\ufff3\017\ufff3\021" +
    "\ufff3\022\061\023\054\024\055\025\057\026\063\027\051" +
    "\030\065\031\047\032\ufff3\033\ufff3\036\ufff3\040\ufff3\041" +
    "\ufff3\042\ufff3\045\ufff3\050\062\055\ufff3\057\ufff3\001\002" +
    "\000\106\002\uffec\004\uffec\005\056\006\046\010\052\011" +
    "\060\012\050\013\053\014\064\015\uffec\016\uffec\017\uffec" +
    "\020\uffec\021\uffec\022\061\023\054\024\055\025\057\026" +
    "\063\027\051\030\uffec\031\uffec\032\uffec\033\uffec\036\uffec" +
    "\037\uffec\040\uffec\041\uffec\042\uffec\045\uffec\050\062\051" +
    "\uffec\055\uffec\057\uffec\001\002\000\044\005\056\006\046" +
    "\010\052\011\060\012\050\013\053\014\064\022\061\023" +
    "\054\024\055\025\057\026\063\027\051\030\065\031\047" +
    "\037\200\050\062\001\002\000\042\004\030\005\007\006" +
    "\027\014\034\016\004\017\031\021\011\032\014\033\026" +
    "\036\022\040\013\041\151\042\016\050\037\055\040\057" +
    "\012\001\002\000\054\002\uffcf\004\uffcf\005\uffcf\006\uffcf" +
    "\014\uffcf\016\uffcf\017\uffcf\021\uffcf\032\uffcf\033\uffcf\034" +
    "\uffcf\036\uffcf\040\uffcf\041\uffcf\042\uffcf\044\uffcf\047\uffcf" +
    "\050\uffcf\055\uffcf\056\uffcf\057\uffcf\001\002\000\106\002" +
    "\uffed\004\uffed\005\uffed\006\uffed\010\uffed\011\uffed\012\050" +
    "\013\uffed\014\064\015\uffed\016\uffed\017\uffed\020\uffed\021" +
    "\uffed\022\uffed\023\uffed\024\uffed\025\uffed\026\uffed\027\uffed" +
    "\030\uffed\031\uffed\032\uffed\033\uffed\036\uffed\037\uffed\040" +
    "\uffed\041\uffed\042\uffed\045\uffed\050\062\051\uffed\055\uffed" +
    "\057\uffed\001\002\000\004\002\ufffc\001\002\000\004\015" +
    "\205\001\002\000\106\002\uffdc\004\uffdc\005\uffdc\006\uffdc" +
    "\010\uffdc\011\uffdc\012\uffdc\013\uffdc\014\uffdc\015\uffdc\016" +
    "\uffdc\017\uffdc\020\uffdc\021\uffdc\022\uffdc\023\uffdc\024\uffdc" +
    "\025\uffdc\026\uffdc\027\uffdc\030\uffdc\031\uffdc\032\uffdc\033" +
    "\uffdc\036\uffdc\037\uffdc\040\uffdc\041\uffdc\042\uffdc\045\uffdc" +
    "\050\uffdc\051\uffdc\055\uffdc\057\uffdc\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\203\000\026\002\017\003\004\004\034\006\022\010" +
    "\016\011\020\012\005\015\032\020\031\021\035\001\001" +
    "\000\002\001\001\000\002\001\001\000\022\004\132\006" +
    "\022\010\016\011\020\012\005\015\202\020\031\021\035" +
    "\001\001\000\006\006\201\020\044\001\001\000\006\006" +
    "\176\020\044\001\001\000\006\006\175\020\044\001\001" +
    "\000\006\006\174\020\044\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\006\164\020\044\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\022\004\132\006\022\010\016\011\020\012\005\015" +
    "\137\020\031\021\035\001\001\000\002\001\001\000\006" +
    "\006\136\020\044\001\001\000\010\006\067\007\135\020" +
    "\044\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\006\133\020\044\001\001\000\014\004" +
    "\127\005\126\006\022\020\031\021\035\001\001\000\002" +
    "\001\001\000\010\006\067\007\121\020\044\001\001\000" +
    "\002\001\001\000\004\022\113\001\001\000\006\006\042" +
    "\020\044\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\006\112\020\044\001\001\000\006" +
    "\006\111\020\044\001\001\000\006\006\110\020\044\001" +
    "\001\000\006\006\107\020\044\001\001\000\006\006\106" +
    "\020\044\001\001\000\006\006\105\020\044\001\001\000" +
    "\006\006\104\020\044\001\001\000\006\006\103\020\044" +
    "\001\001\000\006\006\102\020\044\001\001\000\006\006" +
    "\101\020\044\001\001\000\006\006\100\020\044\001\001" +
    "\000\006\006\077\020\044\001\001\000\006\006\075\020" +
    "\044\001\001\000\006\006\074\020\044\001\001\000\010" +
    "\006\067\007\070\020\044\001\001\000\006\006\065\020" +
    "\044\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\006\073\020\044\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\022\116\001\001\000\002\001\001\000\006\006\120" +
    "\020\044\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\006\124\020\044\001\001\000\002" +
    "\001\001\000\014\004\132\006\022\011\131\020\031\021" +
    "\035\001\001\000\002\001\001\000\014\004\127\005\130" +
    "\006\022\020\031\021\035\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\022\144\001\001\000\002\001\001\000\002\001" +
    "\001\000\016\004\132\006\022\011\147\013\151\020\031" +
    "\021\035\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\022\004\132\006\022\010\016\011\020" +
    "\012\153\014\154\020\031\021\035\001\001\000\002\001" +
    "\001\000\020\004\132\006\022\010\016\011\020\012\155" +
    "\020\031\021\035\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\016\004\132\006\022\011\147" +
    "\013\161\020\031\021\035\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\016" +
    "\004\132\006\022\011\147\013\166\020\031\021\035\001" +
    "\001\000\002\001\001\000\002\001\001\000\016\004\132" +
    "\006\022\011\147\013\171\020\031\021\035\001\001\000" +
    "\002\001\001\000\006\006\173\020\044\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\016\004\132\006\022\011\147\013\200\020\031" +
    "\021\035\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserCup$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserCup$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserCup$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$ParserCup$actions {


	public static List<String> function = new LinkedList<String>();
	public static List<String> variables = new LinkedList<String>();

  private final ParserCup parser;

  /** Constructor */
  CUP$ParserCup$actions(ParserCup parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$ParserCup$do_action(
    int                        CUP$ParserCup$act_num,
    java_cup.runtime.lr_parser CUP$ParserCup$parser,
    java.util.Stack            CUP$ParserCup$stack,
    int                        CUP$ParserCup$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserCup$result;

      /* select the action based on the action number */
      switch (CUP$ParserCup$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // expression_list ::= expression_comma_list 
            {
              Object RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object list = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = list;	
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression_list",17, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // identifier_comma_list ::= 
            {
              Object RESULT =null;
		 RESULT = new LinkedList<String>();	
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("identifier_comma_list",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // identifier_comma_list ::= COMMA IDENTIFIER identifier_comma_list 
            {
              Object RESULT =null;
		int identifierleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int identifierright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object identifier = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object list = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 
										((List<String>)list).add((String)identifier);
										RESULT = list;
									
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("identifier_comma_list",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // target ::= subscription 
            {
              Object RESULT =null;
		int subscriptionleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int subscriptionright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object subscription = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = subscription;	
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("target",15, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // subscription ::= expression LEFTSQUAREBRACKET expression RIGHTSQUAREBRACKET 
            {
              Object RESULT =null;
		int expr1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).left;
		int expr1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).right;
		Object expr1 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).value;
		int expr2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int expr2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object expr2 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		 RESULT = new SubscriptionExpression((Expression)expr1, (Expression)expr2); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("subscription",14, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // statement_list ::= statement 
            {
              Object RESULT =null;
		int stmtleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int stmtright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object stmt = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
										List<Statement> list = new LinkedList<Statement>();
										list.addAll((List<Statement>)stmt);
										RESULT = list;
									
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("statement_list",10, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // statement_list ::= statement_list statement 
            {
              Object RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object list = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int stmtleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int stmtright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object stmt = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
										((List<Statement>)list).addAll((List<Statement>)stmt);
										RESULT = list;
									
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("statement_list",10, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // suite ::= NEWLINE INDENT statement_list DEDENT 
            {
              Object RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object list = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		 RESULT = (List<Statement>)list;	
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("suite",9, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // suite ::= stmt_list NEWLINE 
            {
              Object RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object list = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		 RESULT = (List<Statement>)list;
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("suite",9, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // statement ::= compound_statement 
            {
              Object RESULT =null;
		int stmtleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int stmtright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object stmt = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 
										List<Statement> list = new LinkedList<Statement>();
										list.add((Statement)stmt);
										RESULT = list;
									
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("statement",8, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // statement ::= stmt_list NEWLINE 
            {
              Object RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object list = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		 RESULT = list; 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("statement",8, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // stmt_list ::= simple_statement 
            {
              Object RESULT =null;
		int stmtleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int stmtright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object stmt = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
										List<Statement> list = new LinkedList<Statement>();
										list.add((Statement)stmt);
										RESULT = list;
									
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("stmt_list",7, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // stmt_list ::= simple_statement SEMICOLON stmt_list 
            {
              Object RESULT =null;
		int stmtleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int stmtright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object stmt = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object list = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
										((List<Statement>)list).add((Statement)stmt);
										RESULT = list;
									
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("stmt_list",7, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // compound_statement ::= DEF IDENTIFIER LEFTPARENTHESE IDENTIFIER identifier_comma_list RIGHTPARENTHESE COLON suite 
            {
              Object RESULT =null;
		int identifier1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-6)).left;
		int identifier1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-6)).right;
		Object identifier1 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-6)).value;
		int identifier2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)).left;
		int identifier2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)).right;
		Object identifier2 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)).value;
		int identifierListleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).left;
		int identifierListright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).right;
		Object identifierList = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object list = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 
										interpreter.FunctionsVariables.function.add((String) identifier1);
										((List<String>)identifierList).add((String)identifier2);
										RESULT = new FunctionDefinitionStatement((String)identifier1, (List<String>)identifierList, (List<Statement>)list); 	
									
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("compound_statement",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-7)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // compound_statement ::= DEF IDENTIFIER LEFTPARENTHESE RIGHTPARENTHESE COLON suite 
            {
              Object RESULT =null;
		int identifierleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)).left;
		int identifierright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)).right;
		Object identifier = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object list = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 
										interpreter.FunctionsVariables.function.add((String) identifier);
										RESULT = new FunctionDefinitionStatement((String)identifier, new LinkedList<String>(), (List<Statement>)list); 	
									
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("compound_statement",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-5)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // compound_statement ::= WHILE expression COLON suite 
            {
              Object RESULT =null;
		int exprleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object expr = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object list = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
										RESULT = new WhileStatement((Expression)expr, (List<Statement>)list);
									
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("compound_statement",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // compound_statement ::= IF expression COLON suite 
            {
              Object RESULT =null;
		int exprleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object expr = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object list = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
										RESULT = new IfStatement((Expression)expr, (List<Statement>)list);
									
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("compound_statement",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // compound_statement ::= IF expression COLON suite ELSE COLON suite 
            {
              Object RESULT =null;
		int exprleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-5)).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-5)).right;
		Object expr = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-5)).value;
		int list1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).left;
		int list1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).right;
		Object list1 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).value;
		int list2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int list2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object list2 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
										RESULT = new IfElseStatement((Expression)expr, (List<Statement>)list1, (List<Statement>)list2);
									
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("compound_statement",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-6)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // expression ::= LAMBDA IDENTIFIER identifier_comma_list COLON expression 
            {
              Object RESULT =null;
		int identifierleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).left;
		int identifierright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).right;
		Object identifier = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object list = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int exprleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object expr = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
										((List<String>)list).add((String)identifier);
										RESULT = new LambdaExpression((List<String>)list, (Expression)expr);
									
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // expression ::= LAMBDA COLON expression 
            {
              Object RESULT =null;
		int exprleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object expr = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new LambdaExpression(new LinkedList<String>(), (Expression)expr);	
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // expression ::= expression LEFTPARENTHESE expression_comma_list RIGHTPARENTHESE 
            {
              Object RESULT =null;
		int exprleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).right;
		Object expr = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object list = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		 RESULT = new FunctionExpression((Expression)expr, (LinkedList<Expression>)list);	
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // expression ::= expression LEFTPARENTHESE RIGHTPARENTHESE 
            {
              Object RESULT =null;
		int exprleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object expr = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		 RESULT = new FunctionExpression((Expression)expr, new LinkedList<Expression>());	
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // expression ::= subscription 
            {
              Object RESULT =null;
		int valueleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object value = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = value; 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // expression ::= LEFTSQUAREBRACKET expression_comma_list RIGHTSQUAREBRACKET 
            {
              Object RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object list = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		 RESULT = new ListExpression((List<Expression>)list);	
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // expression ::= IDENTIFIER 
            {
              Object RESULT =null;
		int valueleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object value = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new IdentifierExpression((String)value);	
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // expression ::= FALSE 
            {
              Object RESULT =null;
		 RESULT = new FalseExpression(); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // expression ::= TRUE 
            {
              Object RESULT =null;
		 RESULT = new TrueExpression(); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // expression ::= FLOAT 
            {
              Object RESULT =null;
		int valueleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object value = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new FloatExpression(((String)value)); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // expression ::= INPUT LEFTPARENTHESE RIGHTPARENTHESE 
            {
              Object RESULT =null;
		 RESULT = new InputExpression(); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // expression ::= LEFTPARENTHESE expression RIGHTPARENTHESE 
            {
              Object RESULT =null;
		int exprleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object expr = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		 RESULT = new ParenthesesExpression((Expression)expr); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // expression ::= expression AND expression 
            {
              Object RESULT =null;
		int expr1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int expr1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object expr1 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int expr2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int expr2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object expr2 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new BinaryExpression((Expression) expr1, BinaryOperators.and, (Expression) expr2); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // expression ::= expression OR expression 
            {
              Object RESULT =null;
		int expr1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int expr1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object expr1 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int expr2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int expr2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object expr2 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new BinaryExpression((Expression) expr1, BinaryOperators.or, (Expression) expr2); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // expression ::= expression NOTEQUAL expression 
            {
              Object RESULT =null;
		int expr1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int expr1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object expr1 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int expr2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int expr2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object expr2 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new BinaryExpression((Expression) expr1, BinaryOperators.notequal, (Expression) expr2); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // expression ::= expression LESSOREQUAL expression 
            {
              Object RESULT =null;
		int expr1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int expr1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object expr1 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int expr2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int expr2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object expr2 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new BinaryExpression((Expression) expr1, BinaryOperators.lessorequal, (Expression) expr2); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // expression ::= expression GREATEROREQUAL expression 
            {
              Object RESULT =null;
		int expr1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int expr1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object expr1 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int expr2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int expr2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object expr2 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new BinaryExpression((Expression) expr1, BinaryOperators.greaterorequal, (Expression) expr2); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // expression ::= expression EQUAL expression 
            {
              Object RESULT =null;
		int expr1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int expr1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object expr1 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int expr2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int expr2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object expr2 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new BinaryExpression((Expression) expr1, BinaryOperators.equal, (Expression) expr2); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // expression ::= expression GREATER expression 
            {
              Object RESULT =null;
		int expr1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int expr1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object expr1 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int expr2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int expr2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object expr2 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new BinaryExpression((Expression) expr1, BinaryOperators.greater, (Expression) expr2); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // expression ::= expression LESS expression 
            {
              Object RESULT =null;
		int expr1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int expr1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object expr1 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int expr2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int expr2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object expr2 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new BinaryExpression((Expression) expr1, BinaryOperators.less, (Expression) expr2); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // expression ::= expression POW expression 
            {
              Object RESULT =null;
		int expr1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int expr1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object expr1 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int expr2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int expr2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object expr2 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new BinaryExpression((Expression) expr1, BinaryOperators.pow, (Expression) expr2); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // expression ::= expression MOD expression 
            {
              Object RESULT =null;
		int expr1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int expr1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object expr1 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int expr2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int expr2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object expr2 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new BinaryExpression((Expression) expr1, BinaryOperators.mod, (Expression) expr2); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // expression ::= expression DIV expression 
            {
              Object RESULT =null;
		int expr1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int expr1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object expr1 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int expr2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int expr2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object expr2 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new BinaryExpression((Expression) expr1, BinaryOperators.div, (Expression) expr2); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // expression ::= expression MULT expression 
            {
              Object RESULT =null;
		int expr1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int expr1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object expr1 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int expr2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int expr2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object expr2 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new BinaryExpression((Expression) expr1, BinaryOperators.mult, (Expression) expr2); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // expression ::= expression MINUS expression 
            {
              Object RESULT =null;
		int expr1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int expr1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object expr1 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int expr2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int expr2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object expr2 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new BinaryExpression((Expression) expr1, BinaryOperators.sub, (Expression) expr2); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // expression ::= expression PLUS expression 
            {
              Object RESULT =null;
		int expr1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int expr1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object expr1 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int expr2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int expr2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object expr2 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new BinaryExpression((Expression) expr1, BinaryOperators.add, (Expression) expr2); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // expression ::= NOT expression 
            {
              Object RESULT =null;
		int exprleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object expr = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new UnaryExpression(UnaryOperators.not, (Expression) expr); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // expression ::= PLUS expression 
            {
              Object RESULT =null;
		int exprleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object expr = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new UnaryExpression(UnaryOperators.add, (Expression) expr); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // expression ::= MINUS expression 
            {
              Object RESULT =null;
		int exprleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object expr = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new UnaryExpression(UnaryOperators.sub, (Expression) expr); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // expression ::= INTEGER 
            {
              Object RESULT =null;
		int valueleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object value = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new IntegerExpression((String)value); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // expression_comma_list ::= 
            {
              Object RESULT =null;
		 RESULT = new LinkedList<Expression>();	
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression_comma_list",5, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // expression_comma_list ::= expression 
            {
              Object RESULT =null;
		int exprleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object expr = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 
										List<Expression> list = new LinkedList<Expression>();
										if((Expression)expr != null) {
											list.add((Expression)expr);
										}
										RESULT = list;
									
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression_comma_list",5, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // expression_comma_list ::= expression_comma_list COMMA expression 
            {
              Object RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object list = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int exprleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object expr = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 
										((List<Expression>)list).add((Expression)expr); 
										RESULT = list;
									
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression_comma_list",5, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // simple_statement ::= RETURN expression 
            {
              Object RESULT =null;
		int exprleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object expr = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new ReturnStatement((Expression)expr);	
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("simple_statement",2, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // simple_statement ::= target ASSIGN expression 
            {
              Object RESULT =null;
		int targetleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int targetright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object target = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int exprleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object expr = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new TargetAssignStatement((Expression)target, (Expression)expr);	
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("simple_statement",2, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // simple_statement ::= expression 
            {
              Object RESULT =null;
		int exprleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object expr = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new ExpressionStatement((Expression)expr);	
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("simple_statement",2, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // simple_statement ::= IDENTIFIER ASSIGN expression 
            {
              Object RESULT =null;
		int valueleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object value = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int exprleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object expr = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
										RESULT = new AssignStatement(new IdentifierExpression((String)value), (Expression)expr);
									
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("simple_statement",2, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // simple_statement ::= PASS 
            {
              Object RESULT =null;
		
										RESULT = new PassStatement();
									
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("simple_statement",2, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // simple_statement ::= PRINT expression_comma_list 
            {
              Object RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object list = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 
										RESULT = new PrintStatement((List<Expression>)list); 
									
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("simple_statement",2, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // simple_statement_list ::= 
            {
              Object RESULT =null;
		 RESULT = new LinkedList<Statement>(); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("simple_statement_list",3, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // simple_statement_list ::= simple_statement simple_statement_list 
            {
              Object RESULT =null;
		int stmtleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int stmtright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object stmt = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object list = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
										((List<Statement>)list).add((Statement)stmt);
										RESULT = list;
									
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("simple_statement_list",3, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // statement_newline_list ::= 
            {
              Object RESULT =null;
		 RESULT = new LinkedList<Statement>(); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("statement_newline_list",11, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // statement_newline_list ::= statement statement_newline_list 
            {
              Object RESULT =null;
		int stmtleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int stmtright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object stmt = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object list = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
			
									((List<Statement>)list).addAll((List<Statement>)stmt);
									RESULT = list;
								
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("statement_newline_list",11, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // statement_newline_list ::= NEWLINE statement_newline_list 
            {
              Object RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object list = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = list; 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("statement_newline_list",11, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // module ::= statement_newline_list 
            {
              Object RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object list = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = list; 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("module",1, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // module ::= simple_statement simple_statement_list 
            {
              Object RESULT =null;
		int stmtleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int stmtright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object stmt = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object list = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 ((List<Statement>)list).add((Statement)stmt);
										RESULT = list;
									
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("module",1, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		RESULT = start_val;
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserCup$parser.done_parsing();
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // program ::= module 
            {
              Object RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object list = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 	Collections.reverse((List<Statement>)list);
									RESULT = new Program((List<Statement>)list);
								
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

