
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Sep 26 18:35:47 CEST 2012
//----------------------------------------------------

package parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int POW = 8;
  public static final int MULT = 6;
  public static final int LEFTPARENTHESE = 10;
  public static final int GREATEROREQUAL = 19;
  public static final int UMINUS = 5;
  public static final int INPUT = 12;
  public static final int LEFTSQUAREBRACKET = 38;
  public static final int INTEGER = 13;
  public static final int NOTEQUAL = 21;
  public static final int GREATER = 17;
  public static final int LESS = 16;
  public static final int MINUS = 4;
  public static final int IS = 42;
  public static final int RIGHTCURLYBRACKET = 41;
  public static final int SEMICOLON = 35;
  public static final int NOT = 15;
  public static final int AND = 23;
  public static final int PASS = 32;
  public static final int OR = 22;
  public static final int COMMA = 14;
  public static final int CLASS = 47;
  public static final int DIV = 7;
  public static final int LESSOREQUAL = 20;
  public static final int PLUS = 3;
  public static final int ASSIGN = 33;
  public static final int IF = 26;
  public static final int EOF = 0;
  public static final int RETURN = 45;
  public static final int EQUAL = 18;
  public static final int TRUE = 24;
  public static final int LAMBDA = 43;
  public static final int error = 1;
  public static final int RIGHTPARENTHESE = 11;
  public static final int NEWLINE = 31;
  public static final int MOD = 9;
  public static final int COLON = 29;
  public static final int ELSE = 27;
  public static final int WHILE = 34;
  public static final int DEDENT = 37;
  public static final int FLOAT = 28;
  public static final int FULLSTOP = 46;
  public static final int DEF = 44;
  public static final int LEFTCURLYBRACKET = 40;
  public static final int RIGHTSQUAREBRACKET = 39;
  public static final int FALSE = 25;
  public static final int INDENT = 36;
  public static final int PRINT = 2;
  public static final int IDENTIFIER = 30;
}

